### ISSUE TITLE
Invalid Security Certificate

### ISSUE THREAD

**Issue by hellfyred** [Yara-Rules/yara-endpoint#7]
The website referenced in this repo, https://yararules.com, is using an invalid certificate. The certificate appears to be a wildcard cert for piensasolutions.com. Please see attached image.

![yara-rules-com-bad-cert](https://user-images.githubusercontent.com/4368463/37852233-2d640840-2eb8-11e8-8677-01ce5a50c28b.jpg)

**Comment by Xumeiquer** [comment]
Hi,
Thanks for the issue, this is something with or hosting provider. We are working on it and it will be solved as soon as possible.

**Comment by Xumeiquer** [comment]
This has been solved.
